# Generated by Django 3.0.4 on 2020-05-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='Название')),
                ('completed', models.BooleanField(blank=True, default=False, null=True, verbose_name='Выполнено')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала')),
                ('finish_date', models.DateTimeField(verbose_name='Дата окончания')),
            ],
        ),
    ]
