# Generated by Django 3.0.6 on 2020-05-20 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_tasks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
